const constants = {
  RESET_GAME: "RESET_GAME",
  SHUFFLE_CARDS: "SHUFFLE_CARDS",
  DEAL_CARDS: "DEAL_CARDS",
  START_GAME: "START_GAME",
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",

  BURN_CARD: "BURN_CARD",
  DEAL_FLOP: "DEAL_FLOP",
  DEAL_TURN: "DEAL_TURN",
  DEAL_RIVER: "DEAL_RIVER",
  RANK_HANDS: "RANK_HANDS",
  DECIDE_WINNER: "DECIDE_WINNER",
  
  FOLD_HAND: "FOLD_HAND",
  SHOW_HAND: "SHOW_HAND",
  CHECK_TURN: "CHECK_TURN",
  PLACE_BET: "PLACE_BET",
  CALL_BET: "CALL_BET"
}

export default constants;